<?php

namespace App\Repositories\User;

use App\Interfaces\UserInterface;
use App\Repositories\BaseRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends BaseRepository implements UserInterface
{
    public function findByEmail($email)
    {
        return $this->findOneBy(['email' => $email]);
    }
}
