<?php

namespace App\Repositories\User;

use App\Entities\User;
use App\Interfaces\UserInterface;
use App\Repositories\BaseRepository;
use LaravelDoctrine\ORM\Pagination\PaginatesFromRequest;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends BaseRepository implements UserInterface
{

    use PaginatesFromRequest;

    public function findByEmail($email)
    {
        return $this->findOneBy(['email' => $email]);
    }
}
